services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm ci --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
